sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
  - docker
language: node_js
node_js:
  - '8.1.3'
before_install:
  - ./.travis/main.sh setup-machine
install:
  - ./.travis/main.sh install-packages
after_script:
  - ./.travis/main.sh deploy
script:
  - 'npm run test'
